### ISSUE TITLE
Pure Component

### ISSUE THREAD

**Issue by chunghwanyoon** [jihyuunn/ReactStudy#1]
선생님 질문이 있습니다..

Pure Component 부분 보고 살짝 찾아봤어요

1. 일반적으로 함수형 컴포넌트 작성한다고 했을 때
```javascript
// Mother.js
import React, { useEffect, useState } from "react";
import CustomComponent from "../../components/CustomComponent";

const MotherComponent = () => {

const [something, setSomething] = useState(0);
const [data, setData] = useState(100);

useEffect(() => {
  console.log("mother");
}, [something])

const handleSomethingClick = () => {
  setSomething(something + 1);
}

return (
  <div>
    <CustomComponent data={data} />
    <button onClick={handleSomethingClick} />
  </div>
)
}
```

```javascript
// CustomComponent.js
import React, { useEffect, useState } from "react";

const CustomComponent = data => {

const [do, setDo] = useState("");

useEffect(() => {
  console.log("child");
}) 

return (
  <div>
    <p>blah</p>
  </div>
)
}
```

위와 같은 일반적인 함수형 컴포넌트가 있다고 했을때..
`Mother.js`에서 `handleSomethingClick`으로 state가 변해도 props로 넘기는 `data`는 안변하는데
그래도 `CustomComponent`가 계속 리렌더링 되는건가요..? 

그러면 함수형 컴포넌트를 사용하면 현재로서는 Pure Component처럼 구현은 못하는건가효..? ㅠ.ㅠ

**Comment by jihyuunn** [comment]
근데 일단 setData로 data를 변화시키는 부분이 없는것 아닌가용?
handleSomethingClick은 something state를 변화시키는 거여서 data는 변화하지 않는게 맞는것 같아요

그리고 함수형 pure component는 제가 나중에 추가한 것 같은데 자식 컴포넌트를 React.memo로 감싸면 pure
component처럼 구현이 된다고 합니당
메모이제이션처럼 작동이 된다고 해서 react.memo라고 하는데 props가 똑같으면 컴포넌트 렌더링을 새로 안하고 달라질 때만 새로
렌더링 하는 거래요 ㅋㅋㅋ

export default React.memo(CustumComponent)
이런식으로 쓰면 된다고 합니다..

그 제가 깃헙에 글쓰면서 출처 추가해놨는데 글이 엄청 좋아서 한번 정독하시는거 추천드립니다....
화이팅이고요...

**Comment by chunghwanyoon** [comment]
넵 읽어보겠습니다.. 이 이슈 쓸 당시에 자식 컴포넌트가 여러번 렌더링되길래 찾아보는 와중에 보게되어서 좋았습니당 틈틈이 훔쳐보고 있습니다. 감사합니다~~! 화이탱~!
